### PR TITLE
Delete get_constants, fix get_rankings and supplement get_brawlers

### PR DESCRIPTION
**Pull request by 0dminnimda**
### Added
- `find_brawler` function added to utils
- `find` function added to `Brawlers`
- `MyBox` and `MyBoxList` to also control the behavior of subclasses, such as brawler in brawlers, etc.
### Changed
- `Api.BRAWLERS_URL` -> `Api.BRAWLERS`
- examples now use get_brawlers
### Fixed
- now `get_rankings` works, and handles all cases (earlier errors could occur, for example, if you did not enter `brawler` if `ranking == "brawlers"`)
### Deleted
- `get_constants`
- `Api.CONSTANTS`
- old `Api.BRAWLERS`
- loading in `Api` `Api.BRAWLERS`
- class `Constants`
- `if model == Constants` and its body from `_aget_model` and `_get_model`
- `key` argument from `_aget_model` and `_get_model`
(as unnecessary, get_brawlers replaces this)

# Checklist
- [yes] Docstrings added ([NumpyDoc](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard))
- [yes] If necessary, add to the documentation files
- [yes] Tox checked

### CODE REVIEW

**Comment by SharpBit** [comment]
Your tests aren't running - at least on travis: 


Incorrect test output: 
image
Correct test output:
image


Notice the difference in time: the tests aren't being run

**Comment by SharpBit** [comment]
Not sure if that's due to the changes u had to make to the tox.ini file for python 3.8

**Comment by 0dminnimda** [comment]
@SharpBit everything works, especially since I did not make changes to tox here

**Comment by SharpBit** [comment]
It was broken in the first pull request not this one

**Comment by SharpBit** [comment]
i just didnt notice at the time

**Comment by 0dminnimda** [comment]
@SharpBit so what's wrong?

**Comment by SharpBit** [comment]
Currently fetches brawler when client is initialized- works for users, tests fail though. Constants should not be deleted

**Pull request closed without merging**
