### PR TITLE
Added loop parameter for Client

### PR DESCRIPTION
**Pull request by nihaals**
# Changes Description
A clear and concise description of what the PR changed.

# Type of PR
- [ ] Bug Fix
- [x] Feature Addition

# Checklist
- [x] Docstrings added ([NumpyDoc](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard))
- [ ] If necessary, add to the documentation files
- [ ] Tox checked

### CODE REVIEW

**Comment by fourjr** [comment]
This doesn't even work... 🤔

**Comment by OrangutanGaming** [comment]
This is why you atleast clone the repo instead of doing it online 😄

**Comment by OrangutanGaming** [comment]
If loop isn't given then aiohttp gets it's own loop so you don't have to make your own default.

**Comment by OrangutanGaming** [comment]
Also the way the Client class is made is quite unusual, usually you have 2 separate classes, one being async, that way you have more control over things like typehinting and documentation. That way the paramater would only need to be in one of the classes and you could check the type of the session supplied

**Comment by fourjr** [comment]
add to docstrings

**Comment by SharpBit** [comment]
By the way, the loop parameter only works if the user does not pass in a session.

**Comment by SharpBit** [comment]
I just specified that in the docstring for ya

**Pull request merged**
